// <auto-generated />
using ExamWeb_PhamHuynhTanPhuc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamWeb_PhamHuynhTanPhuc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240627011215_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamWeb_PhamHuynhTanPhuc.Models.DiaNhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<string>("NgheSi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrongNuoc")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DiaNhacs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GiaBan = 105000.0,
                            NgheSi = "Tuấn Vũ",
                            SoLuong = 20,
                            TieuDe = "CD Nỗi buồn gác trọ",
                            TrongNuoc = true
                        },
                        new
                        {
                            Id = 2,
                            GiaBan = 250000.0,
                            NgheSi = "Chế Linh",
                            SoLuong = 15,
                            TieuDe = "CD Bài tình ca đêm",
                            TrongNuoc = true
                        },
                        new
                        {
                            Id = 3,
                            GiaBan = 230000.0,
                            NgheSi = "BABYMONSTER",
                            SoLuong = 10,
                            TieuDe = "CD BABYMONSTER",
                            TrongNuoc = false
                        },
                        new
                        {
                            Id = 4,
                            GiaBan = 150000.0,
                            NgheSi = "Mạnh Quỳnh",
                            SoLuong = 30,
                            TieuDe = "CD Chuyện chúng mình",
                            TrongNuoc = true
                        },
                        new
                        {
                            Id = 5,
                            GiaBan = 27000.0,
                            NgheSi = "Taylor Swift",
                            SoLuong = 10,
                            TieuDe = "CD Today's US-UK Hit ",
                            TrongNuoc = false
                        },
                        new
                        {
                            Id = 6,
                            GiaBan = 220000.0,
                            NgheSi = "Văn Mai Hương",
                            SoLuong = 40,
                            TieuDe = "CD Đoá hồng nhạc việt",
                            TrongNuoc = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
